Samleanmeldelser må kun indeholde unikke faustnumre, ingen dupletter
DBCDK/promat-service pull request #28
Opened 2023-10-30 09:03 UTC by habadbc

2023-10-30 09:31 UTC, jesper-bruun reviewed
Man kunne jo godt have en lille test på tasks, hvor man havde to ens faustnumre.

2023-10-30 09:32 UTC, jesper-bruun approved these changes

2023-10-30 13:29 UTC, habadbc commented
@jesper-bruun  Det har jeg tilføjet i den seneste push :)

2023-11-02 12:01 UTC, hwhadbc commented on service/src/main/java/dk/dbc/promat/service/api/Tasks.java
> +                        new ArrayList<>(new LinkedHashSet<>(List.of(dto.getTargetFausts().toArray(String[]::new))));
Prøv at omskrive denne blok med brug af f.eks. dto.getTargetFausts.stream.distinct e.lign.

2023-11-02 12:08 UTC, hwhadbc commented on service/src/main/java/dk/dbc/promat/service/api/Tasks.java
> +                for (int i = 0; i < noDuplicateFaustNumbers.size(); i++)
Brug range loop i stedet for gl. daws. looping.  (aka. 'enhanced for loop' i java)
https://www.javatpoint.com/for-each-loop

2023-11-02 12:08 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
Flyt den statiske LOGGER initalisering helt op under klassenavnet, og den tomme linie ned mellem LOGGEr og første test

2023-11-02 12:09 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
>          response = putResponse("v1/api/tasks/" + taskWithPrimaryTargetFaust.getId(), dto);
Smid en blank linie ind her, ligesom før - det øger læsbarheden

2023-11-02 12:13 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
> +        // The faustnumbers set earlier in the test
Tom linie oven over en kommentar. Øger læsbarheden

2023-11-02 12:13 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
> +        response = putResponse("v1/api/tasks/" + taskWithPrimaryTargetFaust.getId(), dto);
Tom linie før næste blok af handlinger - øger læsbarheden

2023-11-02 12:14 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
> +        // The list now contains duplicate faustnumbers; 31001111 has two entries
tl. ;)

2023-11-02 12:14 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
> +        // our API call succeeds
tl.

2023-11-02 12:14 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
> +        // Duplicate faustnumbers were removed by the system without notifying the user and the order maintained
tl.

2023-11-02 12:15 UTC, hwhadbc requested changes
Lidt reformattering, ellers fint.

2023-11-02 12:15 UTC, hwhadbc commented on service/src/test/java/dk/dbc/promat/service/api/TasksIT.java
> +
Fedt med mange kommentarer undervejs der forklarer hvorfor og hvad du tester.  nice.

2023-11-06 12:11 UTC, hwhadbc approved these changes
Nice..!

2023-11-08 12:16 UTC, merged